apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    url: postgres:5432
    database: dora_metrics
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
