apiVersion: 1
datasources:
  - name: DORA PostgreSQL
    type: grafana-postgresql-datasource
    uid: DORA_PostgreSQL
    url: postgres:5432
    database: dora_metrics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: dora_metrics
      sslmode: disable
      postgresVersion: 1500
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
